platform :ios, '6.1'

pod 'Archimedes', :head
pod 'ReactiveCocoa', :head
pod 'ReactiveCocoaLayout', :head
pod 'ReactiveMediaPlayer', :path => '../'
pod 'CocoaPlus', :git => 'https://github.com/zakdances/CocoaPlus.git'